config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root 'users#index'

  resources :users, only: [:index] do
    get :download_users, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  require 'uri'

  validates :name, :email, :gender, presence: true
  validates :email, uniqueness: true

  enum gender: { male: 0, female: 1 }

  mount_uploader :picture, PictureUploader

  scope :by_name, ->(name) { where(arel_table[:name].matches("%#{name}%")) }
  scope :pending_download, -> { select { |u| !u.picture_source.nil? && u.picture.file.nil? } }

  class << self
    def bulk_create_from_response(entries)
      users = []

      entries.each do |e|
        users << { name: e[:name][:first] + ' ' + e[:name][:last],
                   gender: genders[e[:gender].to_sym],
                   email: e[:email],
                   picture_source: e[:picture][:large] }
      end

      insert_all users

      PictureDownloadWorker.perform_bulk(User.pending_download.pluck(:id).each_slice(1).to_a)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_scope :by_name

  def index
    @users = apply_scopes(User.all)
    @users = @users.order(:name).page(params[:page]).per(10)
  end

  def download_users
    api_params = { nat: 'br', results: 30, inc: 'gender,name,email,picture', seed: 'giga' }

    response = JSON(RestClient.get('https://randomuser.me/api/', content_type: :json, params: api_params))

    response.deep_symbolize_keys!

    User.bulk_create_from_response response[:results]

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsersList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<div class="d-inline-flex align-items-center pt-5">
  <h1 class=""><%= User.model_name.human.pluralize %></h1>
  <%= link_to download_users_users_path, class: 'mx-2' do %>
    <i class="fas fa-plus-square fa-2x"></i>
  <% end %>
</div>

<%= form_with url: users_url, method: :get do |f| %>
  <div class="row g-3 align-items-center">
    <div class="col-auto">
      <%= f.label :by_name, t('search_by_name') %>
    </div>
    <div class="col-auto">
      <%= f.text_field :by_name, value: params[:by_name], class: 'form-control' %>
    </div>
    <div class="col-auto">
      <%= f.submit class: 'btn btn-primary', id: 'submit' %>
    </div>
    <div class="col-auto">
      <%= link_to users_path(clear: true), class: 'btn btn-danger' do %>
        <i class="fas fa-times fa-1x"></i>
      <% end %>
    </div>
  </div>
<% end %>

<table class="table table-stripped table-hover align-middle">
  <thead class="">
    <th><%= User.human_attribute_name :picture %></th>
    <th><%= User.human_attribute_name :name %></th>
    <th><%= User.human_attribute_name :gender %></th>
    <th><%= User.human_attribute_name :email %></th>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="picture"><%= image_tag(user.picture.url) if user.picture.url %></td>
        <td class="name"><%= user.name %></td>
        <td class="gender"><%= I18n.t user.gender, scope: %i[activerecord attributes user genders] %></td>
        <td class="email"><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>